worlds:
  75310a3a-6bb4-4e0c-8409-9e6648ac7f3e:
    'Ocean Monument Entrance':
      x: -1287.35
      y: 29.56
      z: -7453.77
    'Ocean Monument Bridgehouse':
      x: -1028.48
      y: 63
      z: -7504.92
    'Volcano Ravine':
      x: -588.7
      y: 37
      z: -7990
    'Birch & Brick':
      x: -593.27
      y: 83
      z: -4818.5
    'Anna''s Shipwreck':
      x: -1428.98
      y: 62.52
      z: -7927.83
    'Village by the Ocean Monument':
      x: -684.24
      y: 70
      z: -7960.5
    'Volcano Revine':
      x: -547.74
      y: 22
      z: -7992.49
    'Cottage on the Cliff of the Icebergs':
      x: -910.49
      y: 74
      z: -7357.35
    'Chicken Farm':
      x: -705.96
      y: 67
      z: -8065.75
    'Anotha One Buried Treasure':
      x: -1420.5
      y: 64
      z: -6953.7